battery:
    charge_efficiency: 0.95
    discharge_efficiency: 0.95
    self_discharge: 0.002
    ratio_e2p: 2
    initial_battery_capacity: 0
    size: 4
    battery_cycles: 8000
    replacement_cost_factor: 0.25

pv:
    size: 9
    irradiation: 1253
    performance_ratio: 0.84
    gamma: 0.9


policy:
    fixed_fit: 0.123
    flat_rate_electricity_tariff: 0.29
    electricity_wholesale: 0.0563
    taxes: 0.0371
    component_levy_fit: 0.0768
    is_capacity: False
    is_rtp: False
    is_vfit: False
    capacity_case:
        network_charge: 0
        fixed_capacity: 204
    volumetric_case:
        network_charge: 0.0569
        fixed_capacity: 66

economics:
    discount: 0.05
    lifetime: 20
    invest_pv: 1280
    invest_bat: 1300
    o_and_m_pv: 0.01
    o_and_m_bat: 0.02
    vat: 1.19
    scaling_factor_pv: -0.063
    scaling_factor_battery: -0.153
    optimization_foresight_hours: 24
